### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by smulube** [aren55555/omniauth-dash#1]
Hi, there is no license attached to this code, which means it's impossible for us to use this module in our project. Would you be able to add a license to the code? I'd be happy to submit a PR with a license included if you could tell me what license you'd like to use.

**Comment by aren55555** [comment]
https://github.com/aren55555/omniauth-dash/blob/master/LICENSE.txt

**Comment by smulube** [comment]
that's awesome, thanks for the speedy response!
